INSERT INTO Drinks (`name`, `type`) VALUES
("Achel Bruin",
 "erikoisuus"),
("Achel Extra Bruin",
 "erikoisuus"),
("Boon Oude Geuze",
 "erikoisuus"),
("Brunehaut Ambrée Bio Gluten Free",
 "ale"),
("Brunehaut Blanche Organic Gluten Free",
 "vehnäolut"),
("Brunehaut Saint Martin Blonde",
 "ale"),
("Brunehaut Saint Martin Brune",
 "ale"),
("Caulier Gluten Free Blonde",
 "ale"),
("Caulier Gluten Free Triple",
 "ale"),
("Chimay Blue",
 "erikoisuus"),
("Chimay Grande Réserve Jéroboam 2018",
 "erikoisuus"),
("Chimay Grande Réserve Magnum 2018",
 "erikoisuus"),
("Chimay Grande Réserve Oak Aged Rum Edition 2017",
 "erikoisuus"),
("Chimay Grande Réserve Oak Aged Whisky Edition 2017",
 "erikoisuus"),
("Chimay Première",
 "erikoisuus"),
("Chouffe Cherry",
 "erikoisuus"),
("Chouffe Houblon Dobbelen IPA Tripel",
 "ale"),
("Cuvée des Jacobins Rouge",
 "erikoisuus"),
("De Koninck",
 "ale"),
("De Ranke  XX Bitter",
 "ale"),
("De Ranke Cuvee de Ranke",
 "erikoisuus"),
("De Ranke Guldenberg",
 "ale"),
("De Ranke Guldenberg",
 "ale"),
("De Ranke Kriek de Ranke",
 "erikoisuus"),
("De Ranke Noir de Dottignies",
 "ale"),
("De Ranke Saison de Dottignies",
 "erikoisuus"),
("De Ranke Saison de Dottignies",
 "erikoisuus"),
("De Ranke XX Bitter", ""),
("Duvel",
 "ale"),
("Duvel Tripel Hop Citra",
 "ale"),
("Gauloise Brune",
 "ale"),
("Gouden Carolus Classic", ""),
("Gouden Carolus Cuvée van de Keizer Imperial Dark",
 "ale"),
("Halve Maan Straffe Hendrik Tripel",
 "ale"),
("Hoegaarden Witbier",
 "vehnäolut"),
("Jandrain-Jandrenouille VI Wheat",
 "vehnäolut"),
("Kasteel Donker",
 "ale"),
("La Chouffe",
 "ale"),
("Leffe Blonde",
 "ale"),
("Leffe Brune",
 "ale"),
("Liefmans Glühkriek",
 "erikoisuus"),
("Liefmans Goudenband",
 "erikoisuus"),
("Liefmans Goudenband 2016",
 "erikoisuus"),
("Liefmans Kriek Brut",
 "erikoisuus"),
("Lindemans Blossom Gueuze",
 "erikoisuus"),
("Lindemans Kriek",
 "erikoisuus"),
("Lindemans Oude Gueuze Cuvée René 2017",
 "erikoisuus"),
("Lindemans Oude Kriek Cuvée René 2017",
 "erikoisuus"),
("Maredsous Brune",
 "ale"),
("Mongozo Premium Pilsener",
 "pils"),
("N'Ice Chouffe",
 "ale"),
("Orval",
 "erikoisuus"),
("Oud Beersel Bersalis Sourblend",
 "erikoisuus"),
("Oud Beersel Green Walnut Lambic",
 "erikoisuus"),
("Oud Beersel Oude Geuze Vieille",
 "erikoisuus"),
("Oud Beersel Oude Kriek Vieille",
 "erikoisuus"),
("Petrus Aged Pale",
 "erikoisuus"),
("Rochefort 10",
 "erikoisuus"),
("Rochefort 6",
 "erikoisuus"),
("Rochefort 8",
 "erikoisuus"),
("Rodenbach Caractère Rouge",
 "erikoisuus"),
("Rodenbach Grand Cru",
 "erikoisuus"),
("Rodenbach Vintage 2015",
 "erikoisuus"),
("Saison Dupont",
 "erikoisuus"),
("Saison Dupont",
 "erikoisuus"),
("Saison Dupont Biologique",
 "erikoisuus"),
("St Feuillien Cuveé de Noël",
 "ale"),
("St Feuillien Cuvée de Noël",
 "ale"),
("St. Bernardus Abt 12",
 "ale"),
("St. Bernardus Wit",
 "vehnäolut"),
("St. Feuillien Tripel",
 "ale"),
("Stella Artois",
 "lager"),
("Tilquin Oude Gueuze à l'Ancienne",
 "erikoisuus"),
("Tongerlo Blonde",
 "ale"),
("Val-Dieu Triple",
 "ale"),
("Westmalle Dubbel",
 "erikoisuus"),
("Westmalle Dubbel",
 "erikoisuus"),
("Westmalle Tripel",
 "erikoisuus"),
("Westmalle Tripel",
 "erikoisuus"),
("Arbor Breakfast Stout",
 "stout & porter"),
("Fourpure Deucebox Double IPA tölkki",
 "ale"),
("Fourpure Shape Shifter IPA tölkki",
 "ale"),
("Fuller's & Friends Flora & the Griffin",
 "ale"),
("Fuller's & Friends Peat Souper Smoked Porter",
 "stout & porter"),
("Fuller's & Friends Rebirth",
 "ale"),
("Fuller's 1845",
 "ale"),
("Fuller's ESB Extra Special Bitter",
 "ale"),
("Fuller's Galleon Dry Hopped Lager",
 "lager"),
("Fuller's Golden Pride",
 "erikoisuus"),
("Fuller's Imperial IPA",
 "ale"),
("Fuller's Imperial Stout",
 "stout & porter"),
("Fuller's India Pale Ale",
 "ale"),
("Fuller's London Porter",
 "stout & porter"),
("Fuller's Matariki New Zealand Saison",
 "erikoisuus"),
("Fuller's Organic Honey Dew",
 "ale"),
("Fuller's Past Masters 1905 Old London Ale",
 "ale"),
("Fuller's Past Masters 1981 ESB",
 "ale"),
("Fuller's Vintage Ale 2016",
 "ale"),
("Fuller's Vintage Ale 2018",
 "ale"),
("Fuller's Winter Brew", ""),
("Fullers & Friends New England IPA",
 "ale"),
("Green's Dubbel Ale",
 "ale"),
("Green's Grand India Pale Ale",
 "ale"),
("Green's Great Discovery Amber",
 "ale"),
("Green's Tripel Ale",
 "ale"),
("Little Valley Python IPA",
 "ale"),
("Lyme Bay Traditional Mead",
 "erikoisuus"),
("Magic Rock Dark Arts tölkki",
 "stout & porter"),
("Marston's Old Empire India Pale Ale",
 "ale"),
("Oakham Ales Bishops Farewell",
 "ale"),
("Oakham Ales Green Devil IPA",
 "ale"),
("Redchurch Great Eastern IPA",
 "ale"),
("Redchurch Old Ford Export Stout",
 "stout & porter"),
("Ridgeway Blue Pale Ale Gluten Free",
 "ale"),
("Ridgeway Hamster of Doom",
 "ale"),
("Ridgeway IPA",
 "ale"),
("Robinsons's Old Tom",
 "ale"),
("Samuel Smith Organic Chocolate Stout",
 "stout & porter"),
("Samuel Smith Organic Strawberry Fruit Beer",
 "erikoisuus"),
("Samuel Smith Taddy Porter",
 "stout & porter"),
("Samuel Smith Yorkshire Stingo",
 "ale"),
("Shepherd Neame Christmas Ale",
 "ale"),
("Shepherd Neame India Pale Ale",
 "ale"),
("Shepherd Neame Spitfire",
 "vahva lager"),
("St. Austell Proper Job IPA",
 "ale"),
("St. Peter's Winter Ale",
 "ale"),
("St. Peter´s Cream Stout",
 "stout & porter"),
("Stone's Ginger Joe",
 "erikoisuus"),
("Stone's Ginger Joe Pear",
 "erikoisuus"),
("The London Beer Factory Berliner Heist tölkki",
 "erikoisuus"),
("Theakston Old Peculier",
 "ale"),
("Thornbridge Bear State West Coast IPA",
 "ale"),
("Thornbridge Chiron American Pale",
 "ale"),
("Thornbridge Cocoa Wonderland Chocolate Porter",
 "stout & porter"),
("Thornbridge Crackendale Citra Pale Ale",
 "ale"),
("Thornbridge Fika Cold Brew Coffee Stout", ""),
("Thornbridge Halcyon Imperial IPA",
 "ale"),
("Thornbridge Huck Double IPA",
 "ale"),
("Thornbridge Jaipur IPA",
 "ale"),
("Thornbridge Kipling South Pacific Pale Ale",
 "ale"),
("Thornbridge Melba Peach IPA",
 "ale"),
("Thornbridge Tart Bakewell Sour",
 "erikoisuus"),
("Thornbridge Tonttu Christmas Red Ale",
 "ale"),
("Wild Beer Jambo Imperial Stout",
 "stout & porter"),
("Wild Beer Modus Operandi",
 "erikoisuus"),
("Wild Beer Ninkasi Saison",
 "erikoisuus"),
("Wild Beer Tepache Sour Ale",
 "erikoisuus"),
("Wild Beer Wildebeest",
 "stout & porter"),
("Young's Double Chocolate Stout",
 "stout & porter"),
("Young’s Special London Ale",
 "ale"),
("Ambar Especial",
 "lager"),
("Ambar Radler",
 "erikoisuus"),
("Damm Inedit",
 "erikoisuus"),
("Daura Damm",
 "lager"),
("La Quince & Cervesa Guineu Vanilla Black Velvet 2018",
 "stout & porter"),
("La Quince Hop Fiction",
 "ale"),
("La Quince Llipa!",
 "ale"),
("Mateo & Bernabé Little Bichos Manta",
 "ale"),
("Moritz",
 "lager"),
("Moritz Epidor",
 "vahva lager"),
("Nomada Hanami India Pale Lager",
 "lager"),
("Nomada Petricor",
 "ale"),
("Nomada Revontulet Raspberry Sour Ale",
 "erikoisuus"),
("San Miguel Especial",
 "lager"),
("San Miguel Fresca",
 "lager"),
("Zeta Zendra",
 "erikoisuus"),
("Cape Brewing Amber Weiss",
 "vehnäolut"),
("Cape Brewing Cape of Good Hops Imperial IPA",
 "ale"),
("Cape Brewing Mandarina Bavaria IPA",
 "ale"),
("Jopen Adriaan Wit",
 "vehnäolut"),
("Jopen Apri-Gose in der Hose",
 "erikoisuus"),
("Jopen Doubting Thomas",
 "ale"),
("Jopen Hop Zij Met Ons",
 "ale"),
("Jopen Hoppenbier",
 "erikoisuus"),
("Jopen Jacobus RPA",
 "ale"),
("Jopen Johannieter Weizen Dubbelbock",
 "vehnäolut"),
("Jopen Koyt Gruitbier",
 "erikoisuus"),
("Jopen Northsea IPA",
 "ale"),
("Kees Barrel Project 18.11 tölkki",
 "stout & porter"),
("Kees Barrel Project 18.13 tölkki",
 "stout & porter"),
("Kees Caramel Fudge Stout",
 "stout & porter"),
("Kees Caramel Fudge Stout Woodford Barrel Aged tölkki",
 "stout & porter"),
("Kees Double IPA tölkki",
 "ale"),
("Kees Export Porter 1750",
 "stout & porter"),
("Kees Zeeuwse Bolus Stout tölkki",
 "stout & porter"),
("La Trappe Bockbier",
 "erikoisuus"),
("La Trappe Dubbel",
 "erikoisuus"),
("La Trappe Isid'or",
 "erikoisuus"),
("La Trappe Quadrupel",
 "erikoisuus"),
("La Trappe Tripel",
 "erikoisuus"),
("La Trappe Witte Trappist",
 "vehnäolut"),
("Lowlander Poorter",
 "stout & porter"),
("Lowlander Yuzu & Grapefruit Gose",
 "erikoisuus"),
("Uiltje Dr. Raptor Imperial IPA",
 "ale"),
("Uiltje Mosaic Mammoth",
 "ale"),
("Cobra",
 "lager"),
("Boyne Irish Craft Pale Ale",
 "ale"),
("Guinness Draught 4-Pack tölkki",
 "stout & porter"),
("Guinness Draught tölkki",
 "stout & porter"),
("Porterhouse Oyster Stout",
 "stout & porter"),
("Borg Garún Nr. 19 Icelandic Stout",
 "stout & porter"),
("Borg Saemundur Nr. 49 Mango Pale Ale tölkki",
 "ale"),
("Borg Solveig Nr. 25 Hoppy Weizen tölkki",
 "vehnäolut"),
("Einstök Arctic Pale Ale",
 "ale"),
("Einstök Icelandic Wee Heavy",
 "ale"),
("Einstök Toasted Porter",
 "stout & porter"),
("Einstök White Ale",
 "erikoisuus"),
("Bad Brewer Amber Ale",
 "ale"),
("Bad Brewer IPA",
 "ale"),
("Baladin Isaac",
 "vehnäolut"),
("Baladin Nazionale",
 "ale"),
("Baladin Wayan",
 "erikoisuus"),
("Birrificio Italiano Tipopils",
 "pils"),
("Birrificio del Ducato Beersel Morning",
 "erikoisuus"),
("Birrificio del Ducato Vieille Ville Barriquée",
 "erikoisuus"),
("Doge Go Over Very Bold & Belgian Ale",
 "ale"),
("Doge Keep Up Aesthete Red Lager",
 "lager"),
("Doge Now You Your Time IPA",
 "ale"),
("Doge Take Easy Just a Friendly Blond Lager",
 "lager"),
("Peroni Nastro Azzurro",
 "lager"),
("Toccalmatto B Space Invader",
 "ale"),
("Tre Fontane Tripel",
 "erikoisuus"),
("Brew Age Alphatier New England IPA",
 "ale"),
("Schnaitl Maibock",
 "vahva lager"),
("Stift Engelszell Benno Trappistenbier",
 "erikoisuus"),
("Stift Engelszell Gregorius Trappistenbier",
 "erikoisuus"),
("Stift Engelszell Nivard Trappistenbier",
 "erikoisuus"),
("Asahi Super Dry",
 "lager"),
("Hitachino Nest Anbai Ale",
 "ale"),
("Hitachino Nest Dai Dai IPA",
 "ale"),
("Hitachino Nest Espresso Stout",
 "stout & porter"),
("Hitachino Nest Ginger Ale",
 "erikoisuus"),
("Hitachino Nest Lager",
 "lager"),
("Hitachino Nest Nipponia",
 "ale"),
("Hitachino Nest Pale Ale",
 "ale"),
("Hitachino Nest Red Rice Ale",
 "erikoisuus"),
("Hitachino Nest White Ale",
 "vehnäolut"),
("Hitachino Nest XH Ale",
 "ale"),
("Collective Arts Guava Gose tölkki",
 "erikoisuus"),
("Collective Arts Life in The Clouds Hazy IPA tölkki",
 "ale"),
("Collective Arts Liquid Art Fest IPA tölkki",
 "ale"),
("Collective Arts Radio The Mothership Imperial IPA tölkki",
 "ale"),
("Collective Arts Radio The Mothership Imperial IPA tölkki",
 "ale"),
("Tsingtao Pilsner",
 "pils"),
("Tsingtao Premium Lager",
 "lager"),
("Tsingtao Wheat Beer",
 "vehnäolut"),
("Malduguns Pilota Nakts Porter",
 "stout & porter"),
("Malduguns Sanslide IPA",
 "ale"),
("Uzavas Amber Gold", ""),
("Uzavas Baltic Dark", ""),
("Uzavas Lager", ""),
("Valmiermuiža Baltic Amber Lager",
 "lager"),
("Valmiermuiža Baltic Dark Lager",
 "tumma lager"),
("Valmiermuiža Dark Smoked",
 "erikoisuus"),
("Valmiermuiža Wheat",
 "vehnäolut"),
("Kalnapilis Original",
 "lager"),
("Corona Extra",
 "lager"),
("Sol",
 "lager"),
("Aass Bock",
 "vahva lager"),
("Amundsen Rebel King tölkki",
 "stout & porter"),
("Austmann Mannus & Blodøks Imperial Stout",
 "stout & porter"),
("Austmann Utpå Wit",
 "vehnäolut"),
("Lervig 3 Bean Stout",
 "stout & porter"),
("Nøgne Ø Batch 100",
 "erikoisuus"),
("Nøgne Ø Imperial Rye Porter",
 "stout & porter"),
("Nøgne Ø Imperial Rye Porter",
 "stout & porter"),
("Nøgne Ø India Pale Ale",
 "ale"),
("Ægir Sorachi Saison tölkki",
 "erikoisuus"),
("Perla Kozlak Bockbier",
 "vahva lager"),
("Pinta Imperator Baltycki",
 "stout & porter"),
("Raduga Forbidden Planet",
 "ale"),
("Zywiec",
 "vahva lager"),
("Bal Ambree",
 "erikoisuus"),
("Bal Blonde",
 "ale"),
("Gallia Hefeweizen",
 "vehnäolut"),
("Gallia Lager",
 "lager"),
("Grimbergen Double-Ambrée",
 "ale"),
("Beerbliotek Bobek Citra tölkki",
 "ale"),
("Beerbliotek Hip hops tölkki",
 "ale"),
("Fagerhult Export",
 "lager"),
("Kopparberg Fruit Lager Lemon & Lime",
 "erikoisuus"),
("O/O Muscles Imperial IPA",
 "ale"),
("Omnipollo Aniara Lemon Pale Ale tölkki",
 "ale"),
("Omnipollo Gimbagagompa Imperial Stout",
 "stout & porter"),
("Omnipollo Hypnopompa Imperial Stout",
 "stout & porter"),
("Omnipollo Pleroma Raspberry Crème Brûlée Sour tölkki",
 "erikoisuus"),
("Omnipollo Selassie",
 "stout & porter"),
("Omnipollo Zodiak IPA",
 "ale"),
("Oppigårds Amarillo",
 "ale"),
("Poppels DIPA",
 "ale"),
("Poppels Mörk Lager",
 "tumma lager"),
("Poppels Russian Imperial Stout",
 "stout & porter"),
("Poppels Session Pale Ale",
 "ale"),
("Ricky's IPA",
 "ale"),
("Sofiero Original",
 "lager"),
("Zeunerts Höga Kusten",
 "lager"),
("Zeunerts Merke",
 "lager"),
("Aecht Schlenkerla Rauchbier Märzen",
 "erikoisuus"),
("Aecht Schlenkerla Rauchbier Urbock",
 "erikoisuus"),
("Aecht Schlenkerla Rauchbier Weizen",
 "erikoisuus"),
("Aldersbacher Kloster Dunkel",
 "tumma lager"),
("Andechs Doppelbock Dunkel",
 "vahva lager"),
("Andechs Vollbier Hell",
 "lager"),
("Arcobräu Winterbier",
 "lager"),
("Aventinus Eisbock",
 "vehnäolut"),
("Ayinger Altbairisch Dunkel",
 "tumma lager"),
("Ayinger Celebrator",
 "vahva lager"),
("Ayinger Jahrhundert Bier",
 "lager"),
("Ayinger Urweisse",
 "vehnäolut"),
("Beck's",
 "lager"),
("Benediktiner Hell",
 "lager"),
("Benediktiner Weissbier",
 "vehnäolut"),
("Berliner Kindl Jubiläums Pilsner",
 "pils"),
("Bitburger Premium",
 "lager"),
("Engel Premium Pils",
 "pils"),
("Erdinger Dunkel tölkki",
 "vehnäolut"),
("Erdinger Kristall Weissbier",
 "vehnäolut"),
("Erdinger Pikantus",
 "vehnäolut"),
("Erdinger Weissbier tölkki",
 "vehnäolut"),
("Franziskaner Hefe-Weissbier",
 "vehnäolut"),
("Franziskaner Weissbier Dunkel",
 "vehnäolut"),
("Hacker-Pschorr Munich Gold",
 "lager"),
("Hacker-Pschorr Weisse",
 "vehnäolut"),
("Irlbacher Volksfestbier",
 "lager"),
("Kirin Ichiban",
 "lager"),
("Krombacher Pils",
 "pils"),
("Krombacher Weizen",
 "vehnäolut"),
("Kulmbacher Pils Edelherb",
 "pils"),
("König Pilsener",
 "pils"),
("Löwenbräu Oktoberfestbier",
 "lager"),
("Maisel's Weisse Original",
 "vehnäolut"),
("Mönchshof Bockbier",
 "vahva lager"),
("Neuzeller Bock",
 "vahva lager"),
("Neuzeller Ginger Bier",
 "erikoisuus"),
("Neuzeller Schwarzer Abt",
 "tumma lager"),
("Paulaner Hefe-Weissbier",
 "vehnäolut"),
("Paulaner Oktoberfestbier",
 "lager"),
("Paulaner Salvator",
 "vahva lager"),
("Paulaner Weissbier Kristallklar",
 "vehnäolut"),
("Riedenburger Dolden Bock",
 "vehnäolut"),
("Riedenburger Weizenbock",
 "vehnäolut"),
("Ritterguts German Sour Gose Bock",
 "erikoisuus"),
("Ritterguts Gose Original",
 "erikoisuus"),
("Ritterguts Urgose", ""),
("Schmucker Rosé Bock",
 "vahva lager"),
("Schneider Weisse Tap 6 Mein Aventinus",
 "vehnäolut"),
("Schöfferhofer Hefeweizen",
 "vehnäolut"),
("Spaten München",
 "lager"),
("Spaten Oktoberfestbier",
 "lager"),
("Sünner Kölsch",
 "erikoisuus"),
("Tucher Bajuvator",
 "vahva lager"),
("Tucher Sebaldus Helles Hefe Weizen",
 "vehnäolut"),
("Tucher Urfränkisch Dunkel",
 "tumma lager"),
("Tucher Übersee",
 "lager"),
("Weidmann Weissbier Hefeweizen tölkki",
 "vehnäolut"),
("Weihenstephaner Festbier",
 "lager"),
("Weihenstephaner Hefeweissbier",
 "vehnäolut"),
("Weihenstephaner Hefeweissbier Dunkel",
 "vehnäolut"),
("Weihenstephaner Korbinian",
 "vahva lager"),
("Weihenstephaner Kristall Weissbier",
 "vehnäolut"),
("Weihenstephaner Original Helles",
 "lager"),
("Weihenstephaner Pils",
 "pils"),
("Weihenstephaner Tradition Bayrisch Dunkel",
 "tumma lager"),
("Weihenstephaner Vitus Weizenbock",
 "vehnäolut"),
("Weltenburger Kloster Asam Bock",
 "vahva lager"),
("Wernesgrüner Dark Lager tölkki",
 "tumma lager"),
("Zoller-Hof Fidelis Hefe Hell",
 "vehnäolut"),
("Belhaven 90 Wee Heavy",
 "ale"),
("Belhaven Scottish Stout",
 "stout & porter"),
("Black Isle Organic Goldeneye Pale Ale",
 "ale"),
("Black Isle Organic Hibernator Oatmeal Stout",
 "stout & porter"),
("BrewDog 5 A.M. Saint Red Ale",
 "ale"),
("BrewDog Cocoa Psycho Russian Imperial Stout",
 "stout & porter"),
("BrewDog Dead Pony Club Session Pale Ale",
 "ale"),
("BrewDog Elvis Juice Grapefruit Infused IPA",
 "ale"),
("BrewDog Jack Hammer India Pale Ale tölkki",
 "ale"),
("BrewDog Punk IPA",
 "ale"),
("BrewDog SOS (May Day)",
 "vahva lager"),
("BrewDog Tokyo",
 "stout & porter"),
("Brewdog Al Abordaje!", ""),
("Brewdog Native Son Double IPA tölkki", ""),
("Harviestoun Old Engine Oil",
 "stout & porter"),
("Innis & Gunn Blood Red Sky",
 "ale"),
("Innis & Gunn Gunnpowder IPA",
 "ale"),
("Innis & Gunn Original Barrel Aged",
 "ale"),
("Innis & Gunn Session IPA tölkki",
 "ale"),
("Tempest In The Dark We Live Black IPA",
 "ale"),
("Tempest Marmalade On Rye Double IPA",
 "ale"),
("Tennents Extra",
 "vahva lager"),
("Alberga Ale Capone Red Ale", ""),
("Alberga King's Road",
 "lager"),
("Alberga Pale Ale",
 "ale"),
("Aura Bock 6,5 tölkki",
 "vahva lager"),
("Aura tölkki",
 "lager"),
("Bock's Dunkel",
 "tumma lager"),
("Bock's Heller Bock",
 "vahva lager"),
("Bock's IPA",
 "ale"),
("Bock's India Pale Ale",
 "ale"),
("Bock's Pale Ale",
 "ale"),
("Bock's Pils",
 "pils"),
("Bock's Ruis",
 "erikoisuus"),
("Bock's Talviolut",
 "tumma lager"),
("Brewer's Special Belgian Blonde Ale",
 "ale"),
("Bryggeri Dunkel",
 "tumma lager"),
("Bryggeri Tyrniportteri",
 "stout & porter"),
("Cool Head Heavy Sunshine tölkki",
 "stout & porter"),
("Cool Head IPAnema tölkki",
 "ale"),
("CoolHead & Donut Island Juicy Lucy IIIPA tölkki",
 "ale"),
("CoolHead Over the Galaxies NEIPA tölkki",
 "ale"),
("Donut Island Frisco Disco Citra IPA",
 "ale"),
("Donut Island Ich Bin Ein Berner Grapefruit Gose",
 "erikoisuus"),
("Donut Island Musta Munkki Imperial Stout",
 "stout & porter"),
("Espoon Oma Panimo Cheers From Keilaniemi APA",
 "ale"),
("Fat Lizard  Arctic Fuel IPA tölkki",
 "ale"),
("Fat Lizard 101 California Pale Ale tynnyri",
 "ale"),
("Fat Lizard 51 Roadkill IPA tynnyri",
 "ale"),
("Fat Lizard 51 Roadkill IPA tölkki",
 "ale"),
("Fat Lizard Blacktop Porter tölkki", ""),
("Fat Lizard Cold Brew Blacktop",
 "stout & porter"),
("Fat Lizard Je Suis Saison",
 "erikoisuus"),
("Fat Lizard Raspy Mary Double IPA tölkki",
 "ale"),
("Fat Lizard Saison Rose",
 "erikoisuus"),
("Fat Lizard Sweet Mary Double IPA tölkki",
 "ale"),
("Finlandia Sahti Strong muovipullo",
 "erikoisuus"),
("Finlandia Sahti muovipullo",
 "erikoisuus"),
("Fiskarsin Akvavit Kaffe Stout",
 "erikoisuus"),
("Fiskarsin Funky Luomu",
 "erikoisuus"),
("Fiskarsin Hilpeä Troikka",
 "pils"),
("Fiskarsin Kaffe Stout",
 "stout & porter"),
("Fiskarsin Kaksi Kotia Vailla Humalaa",
 "erikoisuus"),
("Fiskarsin Metsän Henki Kuusenkerkkä-Ale",
 "erikoisuus"),
("Fiskarsin Munkintie",
 "ale"),
("Fiskarsin Musta Valssi",
 "tumma lager"),
("Fiskarsin Paavin Polku",
 "ale"),
("Fiskarsin Pikku Pässi Bock",
 "vahva lager"),
("Flying Dutchman Black is Black And I Want My Baby Back",
 "ale"),
("Flying Dutchman Chubby Santa Got Stuck In The Chimney Stout",
 "stout & porter"),
("Flying Dutchman Mushroom Picking Ass Kicking Matsutake Ale",
 "erikoisuus"),
("Flying Dutchman Strong Minded Brave Hearted Bold As Love",
 "lager"),
("Flying Dutchman The Hibernating Winter Biting Darkness Fighting Imperial IPA",
 "ale"),
("Flying Dutchman Tight Lipped Dry Humored Why So Serious Nordic Berry Sour",
 "erikoisuus"),
("Flying Dutchman Tree Hugging Wood Chopping Mother Nature Loving IPA",
 "ale"),
("Hailuodon Juhlavehnä Luomu",
 "vehnäolut"),
("Hailuodon Märzen Luomu",
 "lager"),
("Hailuodon Pilsneri Luomu",
 "pils"),
("Hiisi Humulus Lupus Double IPA",
 "ale"),
("Hiisi Iku Turso",
 "stout & porter"),
("Hiisi Iku-Turso Tynnyrissä Kypsynyt Imperial Stout",
 "stout & porter"),
("Hiisi Iku-Turso Tynnyrissä Kypsynyt Imperial Stout 2018",
 "stout & porter"),
("Hiisi Inki Ginger Pale Ale",
 "erikoisuus"),
("Hiisi Itse Gooseberry Sour",
 "erikoisuus"),
("Hiisi Kyyttö",
 "stout & porter"),
("Hiisi Leimaus Mango-Habanero IPA",
 "erikoisuus"),
("Hiisi Nuutti Spicy Morning Habanero Stout",
 "stout & porter"),
("Hiisi Otus Vulgaris IPA",
 "ale"),
("Hiisi Raivoava Rakki",
 "ale"),
("Honkavuoren Double Doc Doppelbock",
 "vahva lager"),
("Honkavuoren Heili vehnäolut",
 "vehnäolut"),
("Honkavuoren Pesä Luomulager",
 "lager"),
("Honkavuoren Taiga North Carelian Porter",
 "stout & porter"),
("Honkavuori Taiga Vahva Porter",
 "stout & porter"),
("Hopping Finnjävel",
 "ale"),
("Hopping Flight Cadet",
 "ale"),
("Hopping Thora Gruit Ale",
 "erikoisuus"),
("Hopping Warthog IPA",
 "ale"),
("Humalove Hammer of Sucellus American Barleywine",
 "erikoisuus"),
("Humalove III The Monster Beneath Our Bed",
 "ale"),
("Iso-Kallan Angus Red Ale",
 "ale"),
("Iso-Kallan Oatmeal Stout",
 "stout & porter"),
("Iso-Kallan Pimeyden Morsian Imperial Stout",
 "stout & porter"),
("Iso-Kallan Savo Witbier",
 "vehnäolut"),
("Iso-Kallan Savu Kekri",
 "erikoisuus"),
("Jacobstads Dasher Majestic India Pale Ale",
 "ale"),
("Kakola Riviera IPA",
 "ale"),
("Kanavan Sulku Pils",
 "pils"),
("Karhu 5,3 24-pack tölkki",
 "lager"),
("Karhu 5,3 6-pack tölkki",
 "lager"),
("Karhu 5,3 tölkki",
 "lager"),
("Karhu 5,3 tölkki",
 "lager"),
("Karhu A",
 "lager"),
("Karhu A 8-pack tölkki",
 "lager"),
("Karhu III",
 "lager"),
("Karhu III 6-pack tölkki",
 "lager"),
("Karhu III tynnyri",
 "lager"),
("Karhu III tölkki",
 "lager"),
("Karhu Tosi Vahva 8-pack tölkki",
 "vahva lager"),
("Karhu Tosi Vahva tölkki",
 "vahva lager"),
("Karhu Tosi Vahva tölkki",
 "vahva lager"),
("Karhu Tumma tölkki",
 "tumma lager"),
("Karjala A",
 "lager"),
("Karjala A 6-pack tölkki",
 "lager"),
("Karjala A tölkki",
 "lager"),
("Karjala A tölkki",
 "lager"),
("Karjala IV A 8-pack tölkki",
 "lager"),
("Karjala tölkki",
 "vahva lager"),
("Kiiski Das Boot German Ale",
 "ale"),
("Kiiski Kapina APA 2017",
 "ale"),
("Kiiski Maininki Savuportter",
 "stout & porter"),
("Kiiski Majakka Ale 2017",
 "ale"),
("Kiiski Vastaranta Savulager",
 "lager"),
("Kimito American IPA",
 "ale"),
("Kimito British Rye Ale",
 "erikoisuus"),
("Kimito Mandarina Vehnä",
 "vehnäolut"),
("Kimito Mosaic Vienna",
 "ale"),
("Kimito Rhubarb Sour Saison",
 "erikoisuus"),
("Kimito Smash Series Golden Bikini",
 "ale"),
("Kimito Tropical Thunder Jenkki Lager",
 "lager"),
("Koff III",
 "lager"),
("Koff III 8-pack tölkki",
 "lager"),
("Koff III tölkki",
 "lager"),
("Koff Jouluolut 6-pack tölkki",
 "tumma lager"),
("Koff Jouluolut tölkki",
 "tumma lager"),
("Laitilan Imperiaali Stout",
 "stout & porter"),
("Laitilan Kukko Tuima tölkki",
 "vahva lager"),
("Laitilan Kukko Vahva Pils 12-pack tölkki",
 "pils"),
("Laitilan Kukko Vahva Pils tölkki",
 "pils"),
("Laitilan Kukko Vehnä",
 "vehnäolut"),
("Laitilan Lakritsi Portteri",
 "stout & porter"),
("Lammin Sahti",
 "erikoisuus"),
("Lapin Hanki Spring Bock",
 "vahva lager"),
("Lapin Kulta 2,7",
 "lager"),
("Lapin Kulta A 6-pack tölkki",
 "lager"),
("Lapin Kulta A 8-pack tölkki",
 "lager"),
("Lapin Kulta A tölkki",
 "lager"),
("Lapin Kulta A tölkki",
 "lager"),
("Lapin Kulta III tynnyri",
 "lager"),
("Lapin Kulta Premium III",
 "lager"),
("Lapin Riski Amber Lager",
 "vahva lager"),
("Linden Black IPA", ""),
("Linden Pi.La", ""),
("Maistila Aprikoi Saison",
 "erikoisuus"),
("Maistila Kaira India Pale Ale",
 "ale"),
("Maistila Moood Milk Stout",
 "stout & porter"),
("Maistila Musta Jaska",
 "stout & porter"),
("Maku Brewing APA tölkki",
 "ale"),
("Maku Brewing IPA tölkki",
 "ale"),
("Maku Talvi IPA tölkki",
 "ale"),
("Mallaskosken Black Imperial Rye",
 "erikoisuus"),
("Mallaskosken Imperial Pine Cone Saison",
 "erikoisuus"),
("Mallaskosken Panimo Black IPA",
 "ale"),
("Mallaskosken So Last Saison",
 "erikoisuus"),
("Mallaskosken Summer Night Lager",
 "lager"),
("Mallaskosken True Bock tölkki",
 "vahva lager"),
("Mallaskoski Nemesis 3 Barrel Aged Imperial Rye", ""),
("Mallaskoski Nemesis No. 3",
 "erikoisuus"),
("Mallaskoski True Lager",
 "lager"),
("Mallaskoski Winter Warmer Doppelbock",
 "vahva lager"),
("Mallaskuun Amber Ale",
 "ale"),
("Mallaskuun American Brown Ale",
 "ale"),
("Mallaskuun American Pale Ale",
 "ale"),
("Mallaskuun Black IPA",
 "ale"),
("Mallaskuun Extra Special Bitter",
 "ale"),
("Mallaskuun Peltopyy Pils",
 "pils"),
("Mallaskuun Pumpkin Ale",
 "erikoisuus"),
("Mallassepät Sysi Imperial Stout",
 "stout & porter"),
("Malmgård Arctic Circle Ale",
 "ale"),
("Malmgård Arctic Circle Ale",
 "ale"),
("Malmgård Belge",
 "ale"),
("Malmgård Bock tölkki",
 "vahva lager"),
("Malmgård Dinkel",
 "erikoisuus"),
("Malmgård Emmer IPA",
 "ale"),
("Malmgård Emmer Tripel",
 "ale"),
("Malmgård English IPA",
 "ale"),
("Malmgård Tammipähkinä",
 "stout & porter"),
("Malmgård X-Porter",
 "stout & porter"),
("Marsalkka Pils Luomu tölkki",
 "pils"),
("Marsalkka Tumma Luomu",
 "tumma lager"),
("Marsalkka Vaalea Luomu tölkki",
 "lager"),
("Marsalkka Vahva Luomu tölkki",
 "vahva lager"),
("Mathildedalin Teijo IPA",
 "ale"),
("Mufloni CCCCC IPA",
 "ale"),
("Mufloni Fressewerk",
 "erikoisuus"),
("Mufloni Saison de Randonneur",
 "erikoisuus"),
("Mufloni Sorachi Flamber",
 "ale"),
("Mufloni Äkäpukki Imperial Stout",
 "stout & porter"),
("Mustan Virran Arctic Nights Pale Ale",
 "ale"),
("Mustan Virran Neito Golden Ale",
 "ale"),
("Mustan Virran Pistolekors Porter",
 "stout & porter"),
("Mustan Virran St. Olaf Pale Ale 1.2%",
 "ale"),
("Nordic Brewery Havu 2017",
 "ale"),
("Olvi Export A",
 "lager"),
("Olvi Export A 18-pack tölkki",
 "lager"),
("Olvi Export A 6-pack pullo",
 "lager"),
("Olvi Export A 8-pack tölkki",
 "lager"),
("Olvi Export A tölkki",
 "lager"),
("Olvi Export A tölkki",
 "lager"),
("Olvi III",
 "lager"),
("Olvi IPA Iisalmi Pale Ale tölkki",
 "ale"),
("Olvi Tuplapukki",
 "vahva lager"),
("Olvi Tuplapukki 6-pack tölkki",
 "vahva lager"),
("Olvi Tuplapukki 8-pack tölkki",
 "vahva lager"),
("Olvi Tuplapukki tölkki",
 "vahva lager"),
("Olvi Tuplapukki tölkki",
 "vahva lager"),
("Open Water 100$ Bills",
 "ale"),
("Open Water Farmhouse Ale",
 "erikoisuus"),
("Open Water Lazy IPA",
 "ale"),
("Open Water Paradoxale",
 "ale"),
("Open Water Sea Wasp", ""),
("Open Water Winter Warmer",
 "ale"),
("Plevna Weizenbock",
 "vehnäolut"),
("Polar Monkeys Coordinator APA tölkki",
 "ale"),
("Prykmestar Double IPA",
 "ale"),
("Prykmestar Kahvi Vehnä",
 "vehnäolut"),
("Prykmestar Luomu Pils",
 "pils"),
("Prykmestar NokkosPils tölkki",
 "pils"),
("Prykmestar Oktoberfestbier",
 "lager"),
("Prykmestar Porter",
 "stout & porter"),
("Prykmestar Savu",
 "erikoisuus"),
("Prykmestar Savukataja",
 "erikoisuus"),
("Prykmestar TalviBock",
 "vahva lager"),
("Prykmestar Wehnäbock",
 "vehnäolut"),
("Pyynikin American Ipa",
 "ale"),
("Pyynikin Black IPA",
 "ale"),
("Pyynikin Bourbon Barrel Aged Imperial Stout",
 "stout & porter"),
("Pyynikin KauppaIPA",
 "ale"),
("Pyynikin Pajavasara",
 "stout & porter"),
("Pyynikin Papan Vanilla Stout",
 "stout & porter"),
("Pyynikin Pikkuportteri",
 "stout & porter"),
("Pyynikin Ruby Jazz Ale",
 "ale"),
("Pyynikin Ruby Jazz Ale tölkki",
 "ale"),
("Pyynikin Sessio White Ipa",
 "ale"),
("Pyynikin Stout",
 "stout & porter"),
("Pyynikin Vahvaportteri",
 "stout & porter"),
("Radbrew Buster-Jangle",
 "ale"),
("Radbrew Crossroads",
 "ale"),
("Radbrew Don Of Wasteland Saison",
 "erikoisuus"),
("Radbrew I'll Get Mi Browncoat",
 "ale"),
("Radbrew Ivy Mike Double IPA",
 "ale"),
("Radbrew Sandstone",
 "ale"),
("Radbrew Teapot IPA",
 "ale"),
("Radbrew Wasteland Oasis American Wheat",
 "vehnäolut"),
("Radbrew Wigwam",
 "ale"),
("Rekolan Panimo Funky Luomu",
 "erikoisuus"),
("Rekolan Panimo Kaffe Stout",
 "stout & porter"),
("Rocking Bear Kirvatsin Humalainen IPA",
 "ale"),
("Rocking Bear Tuorsniemi Bitter Ale",
 "ale"),
("Rousal Seawater India Pale Lager",
 "lager"),
("Rousal Sour Apple Weisen",
 "erikoisuus"),
("Ruosniemen Arkkitehti Black IPA",
 "ale"),
("Ruosniemen Artesaani Amber Mosaic Ale",
 "ale"),
("Ruosniemen Diplomi-insinööri Double IPA",
 "ale"),
("Ruosniemen Musta Lomittaja",
 "erikoisuus"),
("Ruosniemen Panimo Betony IPA",
 "ale"),
("Ruosniemen Piirimyyjä American Pale Ale",
 "ale"),
("Ruosniemen Pikkupomo Amber Ale",
 "ale"),
("Ruosniemen Porvari Oloroso Barley Wine",
 "erikoisuus"),
("Ruosniemen Vuorineuvos Cask Edition Imperial Stout",
 "stout & porter"),
("Ruosniemen Vuorineuvos Imperial Stout",
 "stout & porter"),
("Saimaa Brewer's Special Celeia Pilsner tölkki",
 "pils"),
("Saimaa Sun Lager tölkki",
 "lager"),
("Saimaa Vahva tölkki",
 "lager"),
("Saimaan Brewer's Special American IPA tölkki",
 "ale"),
("Saimaan Brewer's Special Ekuanot IPA",
 "ale"),
("Sandels A 8-pack tölkki",
 "lager"),
("Sandels A tölkki",
 "lager"),
("Sandels Special Edition",
 "lager"),
("Sandels Vahva Lager tölkki",
 "vahva lager"),
("Simapaja Innkeeper´s Daughter Hunajasima",
 "erikoisuus"),
("Simapaja Wandering Minstrel kuiva hunajasima",
 "erikoisuus"),
("Sinebrychoff Porter",
 "stout & porter"),
("Sonnisaari Brutis",
 "stout & porter"),
("Sonnisaari Humalaja IPA",
 "ale"),
("Sonnisaari Humalauta IPA",
 "ale"),
("Sonnisaari Kellopeli Mandariini Saison",
 "erikoisuus"),
("Sonnisaari Kojamo Smoked Porter",
 "stout & porter"),
("Sonnisaari Kurantti Black Currant Sour",
 "erikoisuus"),
("Sonnisaari MaiHop Bock",
 "vahva lager"),
("Sonnisaari Mallas Cowboy American Strong Ale", ""),
("Sonnisaari Punk Metal Jacket IPA", ""),
("Sonnisaari Tippa'18 New England DIPA", ""),
("Sonnisaari Vattu Raspberry Sour",
 "erikoisuus"),
("Stadin American Barley Wine",
 "erikoisuus"),
("Stadin American Imperial Porter",
 "stout & porter"),
("Stadin French Saison",
 "erikoisuus"),
("Stadin Gasometer Grapefruit IPA",
 "erikoisuus"),
("Stadin Imperial Pilsner",
 "pils"),
("Stadin Kekri Pils",
 "pils"),
("Stadin Kinkeri",
 "erikoisuus"),
("Stadin Mosaical Extra Pale Ale",
 "ale"),
("Stadin New England IPA", ""),
("Stadin Panimo Whale Ale",
 "ale"),
("Stadin Red Ale",
 "ale"),
("Stadin Savuruis Portteri",
 "erikoisuus"),
("Stadin Stadinhof Weizen", ""),
("Stallhagen Baltic Porter",
 "stout & porter"),
("Suomenlinnan Helsinki Porter",
 "stout & porter"),
("Suomenlinnan Höpken Pils", ""),
("Suomenlinnan Kealakekua IPA",
 "ale"),
("Suomenlinnan Panimo Hoppe IPA",
 "ale"),
("Taiwalkosken Lodurr Strong Ale",
 "ale"),
("Taiwalkosken Näveri",
 "ale"),
("Taiwalkosken Näveri Red Ale",
 "ale"),
("Takatalo & Tompuri Kaski Kylmäsavulager",
 "lager"),
("Takatalo & Tompuri Kaski Savubock",
 "vahva lager"),
("Takatalo & Tompuri Kaski Tuplahumala Pils",
 "pils"),
("Teerenpeli Panimon Erikoinen Nro 4",
 "erikoisuus"),
("Top Fuel Hippie Juice IPA",
 "ale"),
("Top Fuel Lab Genious Porter",
 "stout & porter"),
("Tornion Arctic Pale Ale",
 "ale"),
("Tornion Arctic Stout",
 "stout & porter"),
("Tornion Original 1964",
 "lager"),
("Tuju Export Stout N:O 2",
 "stout & porter"),
("Ylikylä Aino Sparkling Ale",
 "erikoisuus"),
("Ylikylä Ilmari 2016",
 "ale"),
("Ylikylä Ilmari 2016",
 "ale"),
("Ylikylä Osmotar Altbier 2017",
 "erikoisuus"),
("Ylikylä Väinö ESB 2018",
 "ale"),
("BFM Abbaye de Saint Bon Chien",
 "erikoisuus"),
("Amager Buffalo Burlesque",
 "stout & porter"),
("Amager The Bastard Princess Double Dry-Hopped India Pale Ale",
 "ale"),
("Amager Viewpoint",
 "stout & porter"),
("Carlsberg Elephant tölkki",
 "vahva lager"),
("Hornbeer Caribbean Rumstout",
 "stout & porter"),
("Hornbeer Happy Hoppy Viking",
 "ale"),
("Hornbeer Hophorn",
 "ale"),
("Kissmeyer Stockholm Syndrome DIPA",
 "ale"),
("Mikkeller Beer Geek Flat White",
 "stout & porter"),
("Mikkeller Beer Geek Limfjordsporter",
 "stout & porter"),
("Mikkeller Hazeside IPA",
 "ale"),
("Mikkeller I Wish Gluten Free IPA",
 "ale"),
("Mikkeller Porter",
 "stout & porter"),
("Mikkeller Vesterbro Brown Ale",
 "ale"),
("Munkebo Megingjord Barley Wine",
 "erikoisuus"),
("Polar Monkeys White Collar Golden Ale",
 "ale"),
("To Øl Black Ball",
 "stout & porter"),
("To Øl Blossom",
 "erikoisuus"),
("To Øl Lemongrass Gose",
 "erikoisuus"),
("To Øl Mochaccino Messiah Coffee Brown Ale",
 "ale"),
("To Øl Primal Pils",
 "pils"),
("To Øl Raid Beer",
 "pils"),
("To Øl Reparationsbajer",
 "ale"),
("Singha",
 "lager"),
("Bohemia Regent Prezident",
 "lager"),
("Bohemia Regent Zimni Speciál",
 "lager"),
("Celia Dark Gluten Free Lager",
 "tumma lager"),
("Celia Organic Gluten-Free",
 "lager"),
("Herold Czech Black Lager",
 "tumma lager"),
("Holba Premium",
 "lager"),
("Krušovice Cerne",
 "tumma lager"),
("Krušovice Imperial",
 "lager"),
("Litovel Premium tölkki",
 "lager"),
("Novopacké Pivo Podkrkonošský Speciál",
 "tumma lager"),
("Novopacké Pivo Valdštejn",
 "vahva lager"),
("Pardubický Taxis",
 "vahva lager"),
("Pernštejn Granát",
 "tumma lager"),
("Pilsner Urquell",
 "pils"),
("Pilsner Urquell tölkki",
 "pils"),
("Primator Exkluziv",
 "vahva lager"),
("Staropramen Premium",
 "pils"),
("Velkopopovický Kozel Dark",
 "tumma lager"),
("Baltika 6 Porter",
 "stout & porter"),
("Baltika 8 Wheat",
 "vehnäolut"),
("Baltika 9 Extra",
 "vahva lager"),
("Koch Nipperkin Old Ale",
 "ale"),
("Koch Porter",
 "stout & porter"),
("Kolk Näkk Passion Fruit Witbier",
 "vehnäolut"),
("Lehe Suur Paks Mastif Vintage 2016",
 "erikoisuus"),
("Põhjala Cellar Series Ülo Chardonnay Barrel Aged Imperial Saison", ""),
("Põhjala Leevike Spiced Winter Sour",
 "erikoisuus"),
("Põhjala Loits Barrel Aged Imperial Buckwheat Porter",
 "stout & porter"),
("Põhjala Meri Gose",
 "erikoisuus"),
("Põhjala Mets Black Forest IPA",
 "ale"),
("Põhjala Must Kuld Porter",
 "stout & porter"),
("Põhjala Odravein",
 "erikoisuus"),
("Põhjala Reede Double IPA",
 "ale"),
("Põhjala Virmalised IPA",
 "ale"),
("Põhjala Öö",
 "stout & porter"),
("Pühaste Mr Tangerine Man American Wheat Ale",
 "vehnäolut"),
("Saku Antvärk Dark Lager tölkki",
 "tumma lager"),
("Saku Antvärk IPA tölkki",
 "ale"),
("Saku Kuld",
 "lager"),
("Saku Porter",
 "stout & porter"),
("Saku Taurus",
 "vahva lager"),
("Saku Tume",
 "tumma lager"),
("Sori After Ski IPA",
 "ale"),
("Sori Brewing Delirious Imperial IPA",
 "ale"),
("Sori Brewing Hardly Working Pils",
 "pils"),
("Sori Brewing Investor IPA",
 "ale"),
("Sori Brewing Midsummer Melancholy",
 "stout & porter"),
("Sori Brewing Vinum Secale",
 "erikoisuus"),
("Sori Coffee Gorilla Baltic Porter",
 "stout & porter"),
("Sori Dark Humor Club Heaven Hill Barrel Aged",
 "stout & porter"),
("Sori Gracious IPA",
 "ale"),
("Sori Lost Baggage West Coast IPA",
 "ale"),
("Sori We'll Always Have Paris Imperial Stout",
 "stout & porter"),
("Tanker Ketser",
 "erikoisuus"),
("Tanker Reloaded Session IPA",
 "ale"),
("Õllenaut Must Eksport",
 "stout & porter"),
("Õllenaut Sesoon",
 "erikoisuus"),
("Õllenaut Väike Raidur American IPA", ""),
("Öllenaut Sauna Alus",
 "erikoisuus"),
("Anchor Liberty Ale",
 "ale"),
("Anchor Old Foghorn",
 "erikoisuus"),
("Anchor San Franpsycho IPA",
 "ale"),
("Ballast Point Aloha Sculpin Hazy IPA",
 "ale"),
("Ballast Point Fathom IPA",
 "ale"),
("Ballast Point Grapefruit Sculpin IPA",
 "ale"),
("Ballast Point High West Barrel Aged Victory At Sea 2017 2017",
 "stout & porter"),
("Ballast Point Manta Ray Double IPA",
 "ale"),
("Ballast Point Mocha Marlin Winter Release",
 "stout & porter"),
("Ballast Point Peanut Butter Victory At Sea",
 "stout & porter"),
("Ballast Point Pineapple Sculpin IPA",
 "ale"),
("Ballast Point Sculpin IPA",
 "ale"),
("Ballast Point Sour Wench",
 "erikoisuus"),
("Ballast Point Tongue Buckler Imperial Red Ale",
 "ale"),
("Ballast Point Victory at Sea",
 "stout & porter"),
("Boulevard Saison Brett", ""),
("Brooklyn Defender Golden IPA",
 "ale"),
("Brooklyn East India Pale Ale",
 "ale"),
("Brooklyn Lager",
 "lager"),
("Brooklyn Local 2",
 "ale"),
("Brooklyn Sorachi Ace",
 "erikoisuus"),
("Budweiser",
 "lager"),
("Burning Brothers Pyro Pale Ale tölkki",
 "ale"),
("Coors Light",
 "lager"),
("Evil Twin Hipster Ale tölkki",
 "ale"),
("Evil Twin I Always Felt Closer to IPAs Than I Did to People tölkki", ""),
("Evil Twin I Love You with My Stout",
 "stout & porter"),
("Evil Twin Kolata IPA tölkki", ""),
("Evil Twin Lil' B",
 "stout & porter"),
("Evil Twin Low Life Pilsner tölkki",
 "pils"),
("Evil Twin Modern IPA tölkki", ""),
("Evil Twin Molotov Lite Imperial India Pale Ale tölkki",
 "ale"),
("Evil Twin Westbrook Imperial Mexican Biscotti Cake Break",
 "stout & porter"),
("Evil Twin Wet Dream tölkki",
 "ale"),
("Firestone Double Barrel Ale",
 "ale"),
("Firestone Easy Jack IPA",
 "ale"),
("Firestone Pivo Hoppy Pils",
 "pils"),
("Firestone Union Jack IPA",
 "ale"),
("Founders Backwoods Bastard",
 "ale"),
("Founders Barrel Runner",
 "ale"),
("Founders Dankwood",
 "ale"),
("Founders KBS",
 "stout & porter"),
("Founders Lizard of Koz",
 "stout & porter"),
("Founders PC Pils",
 "pils"),
("Great Divide Heyday Modern IPA",
 "ale"),
("Great Divide Yeti Imperial Stout",
 "stout & porter"),
("Kona Fire Rock Pale Ale",
 "ale"),
("Kona Gold Cliff IPA",
 "ale"),
("Lagunitas IPA",
 "ale"),
("Lakefront Eastside Dark Lager",
 "tumma lager"),
("Pizza Port Kook Double IPA tölkki",
 "ale"),
("Pizza Port Ponto Session IPA tölkki",
 "ale"),
("Redhook Long Hammer IPA",
 "ale"),
("Rogue 7 Hop IPA",
 "ale"),
("Rogue Brutal IPA",
 "ale"),
("Rogue Cold Brew 2.0 Coffee Blonde Ale tölkki",
 "ale"),
("Rogue Morimoto Imperial Pilsner",
 "pils"),
("Sierra Nevada Pale Ale",
 "ale"),
("Sierra Nevada Torpedo Extra IPA",
 "ale"),
("Spencer Trappist Ale",
 "erikoisuus"),
("Stone Arrogant Bastard tölkki",
 "ale"),
("Stone Bitter Chocolate Oatmeal Stout",
 "stout & porter"),
("Stone Go To IPA tölkki",
 "ale"),
("Stone IPA tölkki",
 "ale"),
("Stone Imperial Mutt Brown Ale",
 "ale"),
("Stone Old Guardian 2016 Release Barley Wine", ""),
("Stone Ripper tölkki",
 "ale"),
("Stone Ruination Double IPA tölkki",
 "ale"),
("Stone Southern Charred 2015",
 "ale"),
("Stone Totalitarian Imperial Russian Stout",
 "stout & porter"),
("Stone W00t Stout 2018", ""),
("Stone Xocoveza Extra Añejo",
 "stout & porter"),
("SweetWater 420 Extra Pale Ale",
 "ale"),
("SweetWater IPA",
 "ale"),
("Toppling Goliath Hopsmack India Pale Ale",
 "ale"),
("Toppling Goliath Xhops Gold Pale Ale",
 "ale"),
("Two Roads Espressway Cold Brew Coffee Stout",
 "stout & porter"),
("Two Roads Honeyspot Road IPA",
 "ale"),
("Two Roads Lil haven Session IPA",
 "ale"),
("Two Roads Road 2 Ruin Double IPA",
 "ale"),
("Victory Brewing Golden Monkey",
 "ale");